# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/doguk/Documents/RISC-V/matrak-main/episodes/ep5/nexysa7/hw/Nexys-A7-100T-Master.xdc

# IP: ip/clk_50mhz/clk_50mhz.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_50mhz || ORIG_REF_NAME==clk_50mhz} -quiet] -quiet
